# Generated by Django 5.1.3 on 2024-11-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="topic",
            new_name="text",
        ),
    ]
